pipeline {

	agent 	{ 
		label 'docker-jenkinsslave-base' 
	}
			
	tools {
        maven 'MAVEN_3.3.9'
        jdk 'JDK 1.8'
    }
	
    stages {
        stage('Build') { 
            steps {
               echo "Build"
            }
        }
    }
}